# Generated by Django 5.1.5 on 2025-09-21 07:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('art', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('art_name', models.CharField(max_length=50)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.artisan')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('account_number', models.IntegerField(max_length=11)),
                ('account_name', models.CharField(max_length=50)),
                ('bank', models.CharField(max_length=50)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.artisan')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.artisan')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('not paid', 'Not Paid')], max_length=20)),
                ('dateOfpurchase', models.DateTimeField(auto_now_add=True)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.art')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.buyer')),
            ],
        ),
    ]
