# Generated by Django 5.1.5 on 2025-09-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_account_account_number_alter_account_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
